### ISSUE TITLE
downloadUpdate() seems to be broken.

### ISSUE THREAD

**Issue by Rocologo** [InventivetalentDev/Spiget-Update#34]
Im using Spiget Update in my plugins, but downloading new versions using downloadUpdate() seems to be broken. I have updated to your 1.4.5-SNAPSHOT but it still doesnt work.

Each time I call spiget.downloadUpdate() it fails with error 503 no service. hasDirectDownload is true although the link I get actually not is a direct download link ?

downloadUrl = https://spigotmc.org/resources/mobhunting.3582/download?version=449285

I have tried to make my own downloader but has not been able to solve the problem. I get either error 302 or 503 no matter how I try to download. I would be nice if you could take a look at this problem?

**Comment by InventivetalentDev** [comment]
spiget only saves a copy of the latest version of a resource, specific versions are not supported.  
it's pretty tricky to download directly from spigotmc due to cloudflare, unfortunately.

**Comment by Rocologo** [comment]
So the new solution is to download newest version from spiget, using a 

Mobhunting (resource id 3582) : https://api.spiget.org/v2/resources/3582/download

**Comment by InventivetalentDev** [comment]
yes. it should already be doing that, though.

**Comment by Rocologo** [comment]
Sorry did you mean that 1.4.5-SNAPSHOT downloads from spiget instead of spigot.org?

I think I have updated to 1.4.5-SNAPSHOT but I will check.

**Comment by Rocologo** [comment]
Using the spiget URL and not using downloadUpdate(); I solved my problem. 

```
try {
		InputStream in = new URL("https://api.spiget.org/v2/resources/3582/download")
					.openStream();
		Files.copy(in, Paths.get("plugins/MobHunting-" + newDownloadVersion + ".jar"),
					StandardCopyOption.REPLACE_EXISTING);
	} catch (IOException e) {
		e.printStackTrace();
	}
```
